#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define PIN_DHT11 GPIO_NUM_5
#define PIN_MOISTURE ADC1_CHANNEL_7
#define PIN_LUMINESCENCE ADC1_CHANNEL_0
#define PIN_RELAY_LIGHTS GPIO_NUM_32
#define PIN_STATUS_WARN GPIO_NUM_33
#define APP_MQTT_URL CONFIG_ESP_MQTT_URL

#define RELAY_LIGHT 0

#endif /* APP_CONFIG_H */

