#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define PIN_DHT11 GPIO_NUM_5
#define PIN_MOISTURE ADC1_CHANNEL_7
#define PIN_LUMINESCENCE ADC1_CHANNEL_0
#define PIN_RELAY_LIGHTS GPIO_NUM_32

#define RELAY_LIGHT 0

#define APP_ESP_WIFI_SSID CONFIG_ESP_WIFI_SSID
#define APP_ESP_WIFI_PASS CONFIG_ESP_WIFI_PASSWORD
#define APP_ESP_MAXIMUM_RETRY CONFIG_ESP_MAXIMUM_RETRY

#endif /* APP_CONFIG_H */

